
#spring.application.name=user-service
#server.port=8082
#spring.banner.location=classpath:/banners/banner.txt
spring:
  application:
    name:user-service
  banner:
    location:classpath:/banners/banner.txt
server:
  port:8082