

#spring.application.name=sales-service
#server.port=8083
#spring.banner.location=classpath:/banners/banner.txt
spring:
  application:
    name:sales-service
  banner:
    location:classpath:/banners/banner.txt
server:
  port:8083