


#spring.application.name=system-service
#server.port=8085
#spring.banner.location=classpath:/banners/banner.txt
spring:
  application:
    name:system-service
  banner:
    location:classpath:/banners/banner.txt
server:
  port:8085