


#spring.application.name=job-service
#server.port=8084
#spring.banner.location=classpath:/banners/banner.txt
spring:
   application:
      name:job-service
   banner:
      location:classpath:/banners/banner.txt
server:
  port:8084